config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :agencies, param: :name
  resources :pages

  get '/contact-us', to: 'pages#contact'
  get '/', to: 'pages#home'
  root to: 'pages#home'

  mount ForestLiana::Engine => '/forest'



  # I18n - Keep all Routes you add to regular also here
  scope "/:locale" do
    root to: 'pages#home'

    resources :agencies
    resources :pages

    get '/contact-us', to: 'pages#contact'
    get '/:locale' => 'pages#home'
  end






  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/agency.rb
class Agency < ApplicationRecord
  belongs_to :user

  scope :sorted_by, lambda { |sort_option|
    # extract the sort direction from the param value.
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    case sort_option.to_s
    when /^created_at_/
      # Simple sort on the created_at column.
      # Make sure to include the table name to avoid ambiguous column names.
      # Joining on other tables is quite common in Filterrific, and almost
      # every ActiveRecord table has a 'created_at' column.
      order("agencies.created_at #{ direction }")
    when /^name_/
      # Simple sort on the name colums
      order("LOWER(agencies.name) #{ direction }")
    else
      raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
    end
  }

  scope :search_query, lambda { |query|
    # Searches the students table on the 'first_name' and 'last_name' columns.
    # Matches using LIKE, automatically appends '%' to each term.
    # LIKE is case INsensitive with MySQL, however it is case
    # sensitive with PostGreSQL. To make it work in both worlds,
    # we downcase everything.
    return nil  if query.blank?

    # condition query, parse into individual keywords
    terms = query.downcase.split(/\s+/)

    # replace "*" with "%" for wildcard searches,
    # append '%', remove duplicate '%'s
    terms = terms.map { |e|
      (e.gsub('*', '%') + '%').gsub(/%+/, '%')
    }
    # configure number of OR conditions for provision
    # of interpolation arguments. Adjust this if you
    # change the number of OR conditions.
    num_or_conds = 2
    where(
      terms.map { |term|
        "(LOWER(name) LIKE ? OR LOWER(email) LIKE ?)"
      }.join(' AND '),
      *terms.map { |e| [e] * num_or_conds }.flatten
    )
  }

  filterrific(
    default_filter_params: { sorted_by: 'created_at_desc' },
    available_filters: [
      :sorted_by,
      :search_query
    ]
  )
end

app/models/agency_competency.rb
class AgencyCompetency < ApplicationRecord
  belongs_to :competency
  belongs_to :agency
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/competency.rb
class Competency < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :agency
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :agency
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :agency
  belongs_to :competency
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/agencies_controller.rb
class AgenciesController < ApplicationController
  def index
      @filterrific = initialize_filterrific(
        Agency,
        params[:filterrific]
      ) or return
      @agencies = @filterrific.find.page(params[:page])

      respond_to do |format|
        format.html
        format.js
      end
  end

  def show
    @agency = Agency.where(name: params[:name]).first
  end

  def new
    @agency = Agency.new
  end

  def create
    @agency = Agency.create(agency_params)
  end

  def update
  end

  def delete
  end

  def agency_params
      params.require(:agency).permit(
        :name,
        :number_of_staff,
        :annual_revenue,
        :hourly_rate,
        :slogan,
        :description,
        :min_project_size,
        :website,
        :phone,
        :behance_profile,
        :facebook_profile,
        :twitter_profile,
        :linkedin_profile,
        :user_id,
        :email
      )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :set_locale

  def set_locale
    if params[:locale]
      I18n.locale = params[:locale].to_sym || I18n.default_locale
    else
      I18n.locale = I18n.default_locale
    end
  end

  def default_url_options
    { locale: I18n.locale == I18n.default_locale ? nil : I18n.locale }
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/agencies_helper.rb
module AgenciesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/agencies/create.html.erb
<h1>Agencies#create</h1>
<p>Find me in app/views/agencies/create.html.erb</p>

app/views/agencies/delete.html.erb
<h1>Agencies#delete</h1>
<p>Find me in app/views/agencies/delete.html.erb</p>

app/views/agencies/index.html.erb
<%= render 'layouts/shared/header' %>
<br>
<div class="main-container" style="background-color: #FAFAFC">

<div>
  <h3 class="col-sm-10 col-sm-offset-1">We found 201 matching agencies for your search</h2>
</div>


<div class="col-sm-3 col-sm-offset-1">
  <div class="boxed boxed--border">
    <h5>Filters</h5>
<%= form_for_filterrific @filterrific do |f| %>
  <div>
    Search
    <%# give the search field the 'filterrific-periodically-observed' class for live updates %>
    <%= f.text_field(
      :search_query,
      class: 'filterrific-periodically-observed'
    ) %>
  </div>
  <div>
    <%= link_to(
      'Reset filters',
      reset_filterrific_url,
    ) %>
  </div>
  <%# add an automated spinner to your form when the list is refreshed %>
  <%= render_filterrific_spinner %>
<% end %>
    <a class="btn btn--primary" href="#">
      <span class="btn__text">
        Update
      </span>
    </a>
  </div>
</div>

<div class="col-sm-7">
  <div class="boxed boxed--border">
    <p>Tired of searching the right Agency? Let us do the job!</p>
    <div class="card-button">
      <%= link_to("Details", '/') %>
    </div>
  </div>

  <%= render(
    partial: 'layouts/shared/list',
    locals: { agencies: @agencies }
  ) %>

</div>



<div class="col-sm-7">
  <%= render 'layouts/shared/footer' %>
</div>

app/views/agencies/index.js.erb
<%# app/views/students/index.js.erb %>
<% js = escape_javascript(
  render(partial: 'shared/list', locals: { agencies: @agencies })
) %>
$("#filterrific_results").html("<%= js %>");

app/views/agencies/new.html.erb
<h1>Agencies#new</h1>
<p>Find me in app/views/agencies/new.html.erb</p>

app/views/agencies/show.html.erb
<%= render 'layouts/shared/header' %>

<div class="col-sm-10 col-sm-offset-1">
  <div class="media">
    <div class="media-body">
      <div class="media-section">
        <h2>Pictures</h2>
        ...
      </div>
      <div class="media-section">
        <h2>Description</h2>
        <%= @agency.description %>
      </div>
    </div>
    <div class="media-aside">
      <div class="media-section">
        <h2>Share</h2>
        ...
      </div>
      <div class="media-section">
        <h2>382 upvotes</h2>
        ...
      </div>
    </div>
  </div>
</div>

<%= render 'layouts/shared/footer' %>

app/views/agencies/update.html.erb
<h1>Agencies#update</h1>
<p>Find me in app/views/agencies/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:200,300,400,400i,500,600,700" rel="stylesheet">
    <link rel="stylesheet" href="https://s3.amazonaws.com/icomoon.io/114779/Socicon/style.css?c2sn1i">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <script src="https://unpkg.com/flickity@2/dist/flickity.pkgd.js"></script>
    <script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.js"></script>
    <script src="https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/easy-pie-chart/2.1.6/easypiechart.js"></script>
  </body>
</html>

app/views/layouts/shared/_footer.html.erb
            <footer class="text-center-xs space--xs">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-7">
                            <ul class="list-inline">
                                <li> <a href="#"><span class="h6 type--uppercase">About</span></a> </li>
                                <li> <a href="#"><span class="h6 type--uppercase">Careers</span></a> </li>
                                <li> <a href="#"><span class="h6 type--uppercase">Support</span></a> </li>
                            </ul>
                        </div>
                        <div class="col-sm-5 text-right text-center-xs">
                            <ul class="social-list list-inline list--hover">
                                <li><a href="#"><i class="socicon socicon-google icon icon--xs"></i></a></li>
                                <li><a href="#"><i class="socicon socicon-twitter icon icon--xs"></i></a></li>
                                <li><a href="#"><i class="socicon socicon-facebook icon icon--xs"></i></a></li>
                                <li><a href="#"><i class="socicon socicon-instagram icon icon--xs"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-7"> <a class="type--fine-print" href="#">Privacy Policy</a> <a class="type--fine-print" href="#">Legal</a> </div>
                        <div class="col-sm-5 text-right text-center-xs"> <a class="type--fine-print" href="#">support@agencycheck.com</a> </div>
                    </div>
                </div>
            </footer>

app/views/layouts/shared/_header.html.erb
<div class="nav-container">
            <div class="via-1490735413873" via="via-1490735413873" vio="Signup">
                <div class="bar bar--sm visible-xs">
                    <div class="container">
                        <div class="row">
                            <div class="col-xs-3 col-sm-2">
                                <a href="/"> <img class="logo logo-dark" alt="logo" src="img/logo-dark.png"> <img class="logo logo-light" alt="logo" src="img/logo-light.png"> </a>
                            </div>
                            <div class="col-xs-9 col-sm-10 text-right">
                                <a href="#" class="hamburger-toggle" data-toggle-class="#menu1;hidden-xs hidden-sm"> <i class="icon icon--sm stack-interface stack-menu"></i> </a>
                            </div>
                        </div>
                    </div>
                </div>
                <nav id="menu1" class="bar bar-1 hidden-xs">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-1 col-sm-2 hidden-xs">
                                <div class="bar__module">
                                    <a href="/"> <img class="logo logo-dark" alt="logo" src="img/logo-dark.png"> <img class="logo logo-light" alt="logo" src="img/logo-light.png"> </a>
                                </div>
                            </div>
                            <div class="col-md-11 col-sm-12 text-right text-left-xs text-left-sm">
                                <div class="bar__module">
                                    <ul class="menu-horizontal text-left">
                                        <li> <a href="#">
                                        For Agencies
                                    </a> </li>
                                        <li class="dropdown"> <span class="dropdown__trigger">
                                        <%= t('.title') %>
                                    </span>
                                            <div class="dropdown__container">
                                                <div class="container">
                                                    <div class="row">
                                                        <div class="dropdown__content col-md-2">
                                                            <ul class="menu-vertical">
                                                                <li> <a href="#">Single Link</a> </li>
                                                            </ul>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </li>
                                        <li class="dropdown"> <span class="dropdown__trigger">
                                        Agency Categories
                                    </span>
                                            <div class="dropdown__container">
                                                <div class="container">
                                                    <div class="row">
                                                        <div class="dropdown__content col-md-12">
                                                            <div class="col-md-3">
                                                                <h5>Marketing Agency</h5>
                                                                <ul class="menu-vertical">
                                                                    <li> <a href="#">Digital Marketing</a> </li>
                                                                </ul>
                                                            </div>
                                                            <div class="col-md-3">
                                                                <h5>Menu Title</h5>
                                                                <ul class="menu-vertical">
                                                                    <li> <a href="#">Single Link</a> </li>
                                                                </ul>
                                                            </div>
                                                            <div class="col-md-3">
                                                                <h5>Menu Title</h5>
                                                                <ul class="menu-vertical">
                                                                    <li> <a href="#">Single Link</a> </li>
                                                                </ul>
                                                            </div>
                                                            <div class="col-md-3">
                                                                <h5>Menu Title</h5>
                                                                <ul class="menu-vertical">
                                                                    <li> <a href="#">Single Link</a> </li>
                                                                </ul>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                                <div class="bar__module">
                                    <a class="btn btn--sm type--uppercase" href="/users/sign_up"> <span class="btn__text">
                                    Signup</span> </a>
                                    <a class="btn btn--sm btn--primary type--uppercase" href="/users/sign_in"> <span class="btn__text">
                                    Login</span> </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </nav>
            </div>
        </div>

app/views/layouts/shared/_list.html.erb
<div id="filterrific_results">

  <% agencies.each do |agency| %>

    <div class="card boxed boxed--border">

      <div class="card-description">
        <h4><%= agency.name %></h4>
        <span class="type--fade"> <%= agency.slogan %> </span>
        <p> <%= agency.description %> </p>
      </div>

      <p class="card-user">9.8</p>

      <div class="card-button">
        <%= link_to("Details", agency_path(agency.name)) %>
      </div>

    </div>
    <%= render 'layouts/shared/tabs' %>

  <% end %>
</div>

<%= will_paginate agencies %>

app/views/layouts/shared/_tabs.html.erb
<div class="tabs">
  <a class="tab active" href="#">
    <h3>350</h3>
    <p>Followers</p>
  </a>
  <a class="tab" href="#">
    <h3>456</h3>
    <p>Following</p>
  </a>
  <a class="tab" href="#">
    <h3>189</h3>
    <p>Upvoted</p>
  </a>
  <a class="tab" href="#">
    <h3>13</h3>
    <p>Submitted</p>
  </a>
</div>

app/views/pages/contact.html.erb
<%= render 'layouts/shared/header' %>
<div class="main-container">
  <section class="imagebg" data-gradient-bg="#4876BD,#5448BD,#8F48BD,#BD48B1">
    <div class="container">
      <div class="row">
        <div class="col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
          <div class="row">
            <div class="boxed boxed--border">
              <form class="text-left form-email" data-success="Thanks for your enquiry, we'll be in touch shortly." data-error="Please fill in all fields correctly.">
                <div class="col-sm-6"> <label>Name:</label> <input type="text" name="name" class="validate-required"> </div>
                <div class="col-sm-6"> <label>Company:</label> <input type="text" name="company" class="validate-required"> </div>
                <div class="col-sm-6"> <label>Email Address:</label> <input type="email" name="email" class="validate-required validate-email"> </div>
                <div class="col-sm-6"> <label>Phone:</label> <input type="tel" name="phone" class="validate-required"> </div>
                <div class="col-sm-12"> <label>About Project:</label> <textarea rows="5" name="description" class="validate-required"></textarea> </div>
                <div class="col-sm-12 text-center boxed">
                  <h5>Services Required</h5>
                </div>
                <div class="col-sm-3 col-xs-6 text-center"> <label class="block">Design</label>
                  <div class="input-checkbox">
                    <div class="inner"></div> <input type="checkbox" name="design"> </div>
                  </div>
                  <div class="col-sm-3 col-xs-6 text-center"> <label class="block">Development</label>
                    <div class="input-checkbox">
                      <div class="inner"></div> <input type="checkbox" name="dev"> </div>
                    </div>
                    <div class="col-sm-3 col-xs-6 text-center"> <label class="block">Branding</label>
                      <div class="input-checkbox">
                        <div class="inner"></div> <input type="checkbox" name="brand"> </div>
                      </div>
                      <div class="col-sm-3 col-xs-6 text-center"> <label class="block">Marketing</label>
                        <div class="input-checkbox">
                          <div class="inner"></div> <input type="checkbox" name="marketing"> </div>
                        </div>
                        <div class="col-sm-12 text-center boxed">
                          <h5>Approximate Budget</h5>
                        </div>
                        <div class="col-xs-4 text-center">
                          <div class="input-radio"> <label>&lt; $5,000</label>
                            <div class="inner"></div> <input type="radio" name="budget" value="under5k" class="validate-required"> </div>
                          </div>
                          <div class="col-xs-4 text-center">
                            <div class="input-radio"> <label>$5,000 - $10,000</label>
                              <div class="inner"></div> <input type="radio" name="budget" value="5kto10k" class="validate-required"> </div>
                            </div>
                            <div class="col-xs-4 text-center">
                              <div class="input-radio"> <label>$10,000+</label>
                                <div class="inner"></div> <input type="radio" name="budget" value="10kplus" class="validate-required"> </div>
                              </div>
                              <div class="col-sm-12 boxed"> <button type="submit" class="btn btn--primary type--uppercase">Submit Planner</button> </div>
                            </form>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </section>
                <%= render 'layouts/shared/footer' %>
              </div>

app/views/pages/home.html.erb
<%= render 'layouts/shared/header' %>

<div class="main-container">
  <section class="cover imagebg height-70 text-center" data-overlay="4">
    <div class="background-image-holder">
     <!--  <img alt="background" src="img/agency-5.jpg"> -->
      <%= image_tag("agency-5") %>
    </div>
    <div class="container pos-vertical-center">
      <div class="row">
        <div class="col-sm-10 col-md-8">
            <h1>Agency Compare</h1>
            <p class="lead"> Choose the right agency for you or request proposals from the best rated agencies - free and simple </p>
          <div class="boxed boxed--lg bg--white text-left">
            <form class="form--horizontal">
                <div class="col-sm-8"> <input type="text" name="search" placeholder="Type search keywords here"> </div>
                <%= link_to("Search", agencies_path) %>
                <div class="col-sm-4">  </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section>
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-4 padding-card">
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://unsplash.it/240/175/?random');">
            <div class="card-category">Popular</div>
            <div class="card-description">
              <h2>Some stuff</h2>
              <p>Very cool stuff, useful and smart</p>
            </div>
            <%= image_tag("avatar-round-2", class: "card-user avatar") %>
            <a class="card-link" href="#" ></a>
          </div>
        </div>
        <div class="col-xs-12 col-sm-4 padding-card">
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://unsplash.it/240/175/?random');">
            <div class="card-category">Popular</div>
            <div class="card-description">
              <h2>Some stuff</h2>
              <p>Very cool stuff, useful and smart</p>
            </div>
            <%= image_tag("avatar-round-3", class: "card-user avatar") %>
            <a class="card-link" href="#" ></a>
          </div>
        </div>
        <div class="col-xs-12 col-sm-4 padding-card">
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://unsplash.it/240/175/?random');">
            <div class="card-category">Popular</div>
            <div class="card-description">
              <h2>Some stuff</h2>
              <p>Very cool stuff, useful and smart</p>
            </div>
            <%= image_tag("avatar-round-1", class: "card-user avatar") %>
            <a class="card-link" href="#" ></a>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section class="text-center unpad--bottom switchable cta cta-3 space--xs imagebg" data-gradient-bg="#4876BD,#5448BD,#8F48BD,#BD48B1">
    <div class="container">
      <div class="row">
        <div class="col-sm-6 col-md-7">
          <div class="switchable__text">
              <h2>Reinvent how to find your Agency now!</h2>
              <p class="lead"> Create the smart, stylish site your business deserves. </p>
              <a class="btn btn--primary type--uppercase" href="#purchase-template">
              <span class="btn__text">Purchase Stack Now</span>
              <span class="label">$17 USD</span> </a>
          </div>
        </div>
        <div class="col-sm-6 col-md-5 padding">
          <%= image_tag("hero-1", class: "block") %>
          <!--  <img alt="Image" class="block" src="images/avatar-large-1.png">  -->
        </div>
      </div>
    </div>
  </section>
  <section class="switchable feature-large">
    <div class="container">
      <div class="row">
        <div class="col-md-5 col-sm-6 switchable__text">
          <h2>Perfect for bootstrapped startups</h2>
          <p class="lead">Launching an attractive and scalable website quickly and affordably is important for modern startups — Stack offers massive value without looking 'bargain-bin'.</p>
          <a class="btn btn--primary type--uppercase" href="#"><span class="btn__text">Explore Detail</span>
          </a>
        </div>
        <div class="col-md-4 col-sm-6 col-md-pull-1 col-xs-12">
          <div class="boxed boxed--lg boxed--border box-shadow-wide">
            <div class="slider" data-paging="true">
              <ul class="slides">
                <li class="col-xs-12">
                  <div class="feature feature-3 text-center">
                    <i class="icon icon--lg icon-Mail-3 color--primary"></i>
                    <h4>Mailer Integrations</h4>
                    <p> Stack comes with integration for Mail Chimp and Campaign Monitor forms - ideal for modern marketing campaigns</p>
                    <a href="#">Learn More</a>
                  </div>
                </li>
                <li class="col-xs-12">
                  <div class="feature feature-3 text-center"> <i class="icon icon--lg icon-Air-Balloon color--primary"></i>
                    <h4>Diverse Icons</h4>
                    <p>Including the premium Icons Mind icon kit, Stack features a highly diverse set of icons suitable for all purposes.</p>
                    <a href="#">Learn More</a>
                  </div>
                </li>
                <li class="col-xs-12">
                  <div class="feature feature-3 text-center"> <i class="icon icon--lg icon-Bacteria color--primary"></i>
                      <h4>Modular Design</h4>
                      <p> Combine blocks from a range of categories to build pages that are rich in visual style and interactivity</p>
                      <a href="#">Learn More</a>
                  </div>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section class="space--xs imagebg" data-gradient-bg="#4876BD,#5448BD,#8F48BD,#BD48B1">
    <div class="container">
      <div class="row">
        <div class="cta cta--horizontal text-center-xs">
          <div class="col-sm-4">
              <h4>Let's get you started</h4>
          </div>
          <div class="col-sm-5">
              <p class="lead"> Find your preferred agency in five minutes!</p>
          </div>
          <div class="col-sm-3 text-right text-center-xs">
              <a class="btn btn--primary type--uppercase" href="#"> <span class="btn__text">
          Start now</span> </a>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section class="imagebg" data-overlay="4">
    <div class="background-image-holder">
      <!--  <img alt="background" src="img/hero-1.jpg">  -->
      <%= image_tag("hero-1") %>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <div class="slider slider--inline-arrows" data-arrows="true">
            <ul class="slides">
              <li>
                <div class="row">
                  <div class="testimonial">
                    <div class="col-md-2 col-md-offset-1 col-sm-4 col-xs-6 text-center">
                      <!-- <img class="testimonial__image" alt="Image" src="img/avatar-round-1.png"> -->
                      <%= image_tag("avatar-round-1", class: "testimonial__image") %>
                    </div>
                    <div class="col-md-7 col-md-offset-1 col-sm-8 col-xs-12">
                      <span class="h3">“We’ve been using Stack to prototype designs quickly and efficiently. Needless to say we’re hugely impressed by the style and value.”</span>
                      <h5>Maguerite Holland</h5>
                      <span>Interface Designer — Yoke</span>
                    </div>
                  </div>
                </div>
              </li>
              <li>
                <div class="row">
                  <div class="testimonial">
                    <div class="col-md-2 col-md-offset-1 col-sm-4 col-xs-6 text-center">
                     <!--  <img class="testimonial__image" alt="Image" src="img/avatar-round-4.png"> -->
                      <%= image_tag("avatar-round-4", class: "testimonial__image") %>
                    </div>
                    <div class="col-md-7 col-md-offset-1 col-sm-8 col-xs-12">
                      <span class="h3">“I've been using Medium Rare's templates for a couple of years now and Stack is without a doubt their best work yet. It's fast, performant and absolutely stunning.”
                      </span>
                      <h5>Lucas Nguyen</h5> <span>Freelance Designer</span>
                    </div>
                  </div>
                </div>
              </li>
              <li>
                <div class="row">
                  <div class="testimonial">
                    <div class="col-md-2 col-md-offset-1 col-sm-4 col-xs-6 text-center">
                      <!-- <img class="testimonial__image" alt="Image" src="img/avatar-round-3.png"> -->
                      <%= image_tag("avatar-round-3", class: "testimonial__image") %>
                    </div>
                    <div class="col-md-7 col-md-offset-1 col-sm-8 col-xs-12">
                      <span class="h3">“Variant has been a massive plus for my workflow — I can now get live mockups out in a matter of hours, my clients really love it.”</span>
                      <h5>Rob Vasquez</h5>
                      <span>Interface Designer — Yoke</span>
                    </div>
                  </div>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </section>
<%= render 'layouts/shared/footer' %>
</div>